const Image = require('../models/imagemodel');
const { uploadFileToS3, deleteFileFromS3 } = require('../services/s3Service');

exports.uploadImage = async (req, res) => {
    if (!req.file) {
        return res.status(400).json({ message: 'No image uploaded' });
    }
    try {
        // Pass req.user.id to organize image under images/{user_id}/ in S3
        const imageUrl = await uploadFileToS3(req.file, req.user.id);  // URL generated by S3
        const image = await Image.create({
            file_name: req.file.originalname,
            url: imageUrl,
            user_id: req.user.id,
            upload_date: new Date()
        });
        res.status(201).json(image);
    } catch (error) {
        res.status(500).json({ error: 'Failed to upload image', details: error.message });
    }
};

exports.getImage = async (req, res) => {
    try {
        const image = await Image.findOne({ where: { user_id: req.user.id } });
        if (!image) {
            return res.status(404).json({ message: 'Image not found' });
        }
        res.json(image);
    } catch (error) {
        res.status(500).json({ error: 'Failed to retrieve image', details: error.message });
    }
};

exports.deleteImage = async (req, res) => {
    try {
        const image = await Image.findOne({ where: { user_id: req.user.id } });
        if (!image) {
            return res.status(404).json({ message: 'Image not found' });
        }
        // Use images/{user_id}/{file_name} for deleteFileFromS3 to locate and delete the image
        const fileKey = `images/${req.user.id}/${image.file_name}`;
        await deleteFileFromS3(fileKey);   
        await image.destroy();
        res.status(204).send();
    } catch (error) {
        res.status(500).json({ error: 'Failed to delete image', details: error.message });
    }
};