name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATA_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DATA_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        PORT: ${{ secrets.PORT }}
        DATA_DIALECT: ${{ secrets.DATA_DIALECT }}
        DATA_HOST: localhost
        DATA_PORT: ${{ secrets.DATA_PORT }}
        DATA_USER: ${{ secrets.DATA_USER }}
        DATA_PASSWORD: ${{ secrets.DATA_PASSWORD }}
        DATA_DATABASE: ${{ secrets.DATA_DATABASE }}
      run: npm test