name: Check

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: devtest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "no"
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATA_PASSWORD }}   
          MYSQL_DATABASE: ${{ secrets.DATA_DATABASE }}           
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    # Configure MySQL bind-address to allow external connections
    - name: Configure MySQL bind-address
      run: |
        echo "[mysqld]" >> /etc/mysql/my.cnf
        echo "bind-address = 0.0.0.0" >> /etc/mysql/my.cnf
        sudo systemctl restart mysql

    # Wait for MySQL to be ready
    - name: Wait for MySQL to be ready
      run: |
        sudo apt-get install mysql-client -y
        until mysqladmin ping -h ${{ secrets.DATA_HOST }} --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    # Create MySQL User 'aayush' and grant privileges
    - name: Setup MySQL User and Database
      run: |
        mysql -h ${{ secrets.DATA_HOST }} -u root --password=${{ secrets.DATA_PASSWORD }} -e "CREATE USER IF NOT EXISTS 'aayush'@'%' IDENTIFIED BY '${{ secrets.DATA_PASSWORD }}';"
        mysql -h ${{ secrets.DATA_HOST }} -u root --password=${{ secrets.DATA_PASSWORD }} -e "GRANT ALL PRIVILEGES ON *.* TO 'aayush'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"
        mysql -h ${{ secrets.DATA_HOST }} -u root --password=${{ secrets.DATA_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DATA_DATABASE }};"

    # Test MySQL connection with 'aayush'
    - name: Test MySQL Connection
      run: |
        mysql -h ${{ secrets.DATA_HOST }} -u aayush --password=${{ secrets.DATA_PASSWORD }} -e "SHOW DATABASES";

    - name: Run Jest tests
      run: npm test
      env:
        DATA_DIALECT: mysql
        DATA_HOST: ${{ secrets.DATA_HOST }}
        DATA_USER: aayush
        DATA_PASSWORD: ${{ secrets.DATA_PASSWORD }}
        DATA_DATABASE: ${{ secrets.DATA_DATABASE }}
        DATA_PORT: ${{ secrets.DATA_PORT }}

    - name: Check MySQL logs if failed
      if: failure()
      run: docker logs $(docker ps -q --filter ancestor=mysql:8.0)