name: Run Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${{ secrets.DATA_PASSWORD }}   
      DB_SCHEMA: ${{ secrets.DATA_DATABASE }}  

    steps:
       
      - uses: actions/checkout@v2

       
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo /lib/systemd/systemd-sysv-install enable mysql
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service

       
      - name: Verify MySQL is Running
        run: |
          sudo systemctl status mysql.service
          sudo mysql --version

      
      - name: Set up MySQL Database
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${{ secrets.DATA_PASSWORD }}';"
          sudo mysql -u root --password=${{ secrets.DATA_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DATA_DATABASE }};"  
        
       
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      
      - name: Install Dependencies
        run: npm install

      
      - name: Run Integration Tests
        env:
          PORT: ${{ secrets.PORT }}  
          DATA_DIALECT: ${{ secrets.DATA_DIALECT }}  
          DATA_HOST: ${{ secrets.DATA_HOST }}   
          DATA_PORT: ${{ secrets.DATA_PORT }}   
          DATA_USER: ${{ secrets.DATA_USER }}   
          DATA_PASSWORD: ${{ secrets.DATA_PASSWORD }}   
          DATA_DATABASE: ${{ secrets.DATA_DATABASE }}   
        run: npm test

      
      - run: echo "Integration tests passed successfully!"