name: Run Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    environment: devtest   

    steps:
       
      - uses: actions/checkout@v2

       
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service

       
      - name: Verify MySQL is Running
        run: |
          sudo systemctl status mysql.service
          sudo mysql --version

      
      
      - name: Configure MySQL User
        run: |
          sudo mysql -e "ALTER USER 'root'@'127.0.0.1' IDENTIFIED WITH 'mysql_native_password' BY 'Aayush@456';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Create Database
        run: |
          sudo mysql -u root --password="Aayush@456" -e "CREATE DATABASE IF NOT EXISTS \`${{ env.DATA_DATABASE }}\`;"

       
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

       
      - name: Install Dependencies
        run: npm install

       
      - name: Run Integration Tests
        env:
          PORT: ${{ env.PORT }}  
          DATA_DIALECT: ${{ env.DATA_DIALECT }}
          DATA_HOST: ${{ env.DATA_HOST }}
          DATA_PORT: ${{ env.DATA_PORT }}
          DATA_USER: root
          DATA_PASSWORD: Aayush@456
          DATA_DATABASE: ${{ env.DATA_DATABASE }}
        run: npm test

       # test
      - run: echo "Integration tests passed successfully!"