name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: devtest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATA_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DATA_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Wait for MySQL
      run: |
        until nc -z 127.0.0.1 3306; do
          echo "waiting for MySQL..."
          sleep 1
        done

    - name: Run tests
      env:
        PORT: ${{ env.PORT }}
        DATA_DIALECT: ${{ env.DATA_DIALECT }}
        DATA_HOST: localhost
        DATA_PORT: 3306
        DATA_USER: root
        DATA_PASSWORD: ${{ secrets.DATA_PASSWORD }}
        DATA_DATABASE: ${{ env.DATA_DATABASE }}
      run: npm test