name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    environment: devtest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      AMI_USERS: ${{ secrets.AMI_USERS }}
      AWS_DEFAULT_REGION: "us-east-1"
     
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          
      - name: Create zip  
        run: |
              
              zip -r webapp.zip .   

      - name: Upload the application artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ./webapp.zip

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp

     
      - name: Install Packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
            packer-version: 1.11.2
  
      - name: Initialize Packer
        run: |
            packer init $GITHUB_WORKSPACE/packer/template.pkr.hcl
      - name: Build Packer Template
        run: 
          packer build \
          -var "source_ami=${{ secrets.SOURCE_AMI }}" \
          -var "subnet_id=${{ secrets.SUBNET_ID }}" \
          -var "ami_users=${{ fromJson(secrets.AMI_USERS) }}" \
          packer build $GITHUB_WORKSPACE/packer/template.pkr.hcl
       