name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: pkr_status_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build and zip the application
        run: |
          zip -r webapp.zip .   

      - name: Upload the application artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ./webapp.zip

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp

      - name: Install Packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          packer-version: 1.11.2
       
      - name: Run packer init
        run: packer init $GITHUB_WORKSPACE/packer/template.pkr.hcl

      - name: Run packer fmt
        run: |
          packer fmt -check -diff $GITHUB_WORKSPACE/packer  

      - name: Validate Packer template
        run: packer validate $GITHUB_WORKSPACE/packer/template.pkr.hcl   

      