name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: pkr_status_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          packer-version: 1.11.2
      - name: Zip Webapp folder
        run: |
            cd $GITHUB_WORKSPACE
            zip -r webapp.zip Webapp   
  
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v3
        with:
            name: webapp-zip
            path: $GITHUB_WORKSPACE/webapp.zip  
      - name: Run packer init
        run: packer init $GITHUB_WORKSPACE/packer/template.pkr.hcl

      - name: Run packer fmt
        run: |
          packer fmt -check -diff $GITHUB_WORKSPACE/packer  

      - name: Validate Packer template
        run: packer validate $GITHUB_WORKSPACE/packer/template.pkr.hcl   

      