name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}   
      DATA_DIALECT: ${{ secrets.DATA_DIALECT }}
      DATA_HOST: ${{ secrets.DATA_HOST }}
      DATA_PORT: ${{ secrets.DATA_PORT }}
      DATA_USER: ${{ secrets.DATA_USER }}
      DATA_PASSWORD: ${{ secrets.DATA_PASSWORD }}
      DATA_DATABASE: ${{ secrets.DATA_DATABASE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build and zip the application
        run: |
         zip -r webapp.zip .   

      - name: Upload the application artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ./webapp.zip

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp
       
      - name: Install Packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
            packer-version: 1.11.2
  
      - name: Initialize Packer
        run: |
            packer init packer/template.pkr.hcl
      - name: Build AMI using Packer
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-east-1"
        run: |
              packer build packer/template.pkr.hcl
       