name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    environment: devtest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"
      PORT: ${{ secrets.PORT }}   
      DATA_DIALECT: ${{ secrets.DATA_DIALECT }}
      DATA_HOST: ${{ secrets.DATA_HOST }}
      DATA_PORT: ${{ secrets.DATA_PORT }}
      DATA_USER: ${{ secrets.DATA_USER }}
      DATA_PASSWORD: ${{ secrets.DATA_PASSWORD }}
      DATA_DATABASE: ${{ secrets.DATA_DATABASE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      - name: Create .env file and zip it 
        run: |
              touch $GITHUB_WORKSPACE/.env
              echo "DB_HOST=$DATA_HOST" >> .env
              echo "DB_PORT=$DATA_PORT" >> .env
              echo "DB_USER=$DATA_USER" >> .env
              echo "DB_PASSWORD=$DATA_PASSWORD" >> .env
              echo "DB_SCHEMA=$DATA_DATABASE" >> .env
              echo "DB_DIALECT=$DATA_DIALECT" >> .env
              echo "PORT=$PORT" >> .env
              cat .env
              zip -r webapp.zip .   

      - name: Upload the application artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ./webapp.zip

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp

     
      - name: Install Packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
            packer-version: 1.11.2
  
      - name: Initialize Packer
        run: |
            packer init $GITHUB_WORKSPACE/packer/template.pkr.hcl
      - name: Build Packer Template
        run: packer build $GITHUB_WORKSPACE/packer/template.pkr.hcl
       